version: "3"
services:
  pg_master_1:
     build: ./master
     ports:
         - "5445:5432"
     volumes:
         - mdata:/var/lib/postgresql/data
     environment:
         - POSTGRES_USER=optima
         - POSTGRES_PASSWORD=123456
         - POSTGRES_DB=postgres
         - PG_REP_USER=rep
         - PG_REP_PASSWORD=123456
     networks:
           - bridge-docker
     restart: always
  pg_slave_1:
     build: ./slave
     ports:
         - "5446:5432"
     volumes:
         - sdata:/var/lib/postgresql/data
     environment:
         - POSTGRES_USER=optima
         - POSTGRES_PASSWORD=123456
         - POSTGRES_DB=postgres
         - PG_REP_USER=rep
         - PG_REP_PASSWORD=123456
     networks:
            - bridge-docker
     restart: always
  pg_slave_2:
      build: ./slave
      ports:
          - "5447:5432"
      volumes:
          - sdata:/var/lib/postgresql/data2
      environment:
          - POSTGRES_USER=optima
          - POSTGRES_PASSWORD=123456
          - POSTGRES_DB=postgres
          - PG_REP_USER=rep
          - PG_REP_PASSWORD=123456
      networks:
             - bridge-docker
      restart: always
  proxy:
    container_name: haproxy
    #image: haproxy
    build: ./haproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - pg_master_1
      - pg_slave_1
      - pg_slave_2
    ports:
      - "15432:5000"
      - "15433:5001"
      - "7000:7000"
    networks:
      - bridge-docker
volumes:
  mdata:
  sdata:
networks:
  bridge-docker:
    external:
      name: bridge-docker
